### ISSUE TITLE
Broken since today?

### ISSUE THREAD

**Issue by talizea** [vekvoid/UserScripts#1]
Looks like instagram changed something, a few other scripts (download related) stopped working as well.

**Comment by vekvoid** [comment]
Thanks. Working on it.

**Comment by vekvoid** [comment]
Fixed in 1.0.1.

Instagram is making changes to its layout, so it could stop working again. If it happens feel free to reopen the issue.

**Comment by talizea** [comment]
and it looks broken again :(

**Comment by vekvoid** [comment]
Fixed in 1.1.1

**Comment by talizea** [comment]
they changed the desktop layout again (and apparently broke this script)

**Comment by vekvoid** [comment]
It is working for me with the new side menu layout. I tried with another browser and account.

Are you using version `1.1.2`?

**Comment by talizea** [comment]
Yep, and it worked with the new menu on the left, but for me stopped working after they moved the stories from top to right side.

**Comment by vekvoid** [comment]
Oh, I don't have this new change. I will open a new issue and fix it as son as I get the new layout.
