### ISSUE TITLE
[Instagram Auto Like] Broken with stories at right side

### ISSUE THREAD

**Issue by vekvoid** [vekvoid/UserScripts#3]
Waiting to see the new changes to be able to fix it.

Originally reported by @talizea in https://github.com/vekvoid/UserScripts/issues/1#issuecomment-1298367856

**Comment by vekvoid** [comment]
I haven't received the update yet. If someone can provide the homepage html I could work with that but it will require some help for testing.

**Comment by vekvoid** [comment]
Closing as I wasn't able to reproduce.

**Comment by talizea** [comment]
yeah, that seemed to be one of their beta tests, it reverted to the old layout after 2-3 weeks.
