### ISSUE TITLE
[Twitch Pinned Streamers] Bugs

### ISSUE THREAD

**Issue by topfishowo** [vekvoid/UserScripts#4]
I really need this feature. There are some bugs:
1.It often doesn't trigger; there is a chance it will only appear normally when the cursor is placed above.
2.Channel status doesn't update regularly, including changes in the number of viewers and the streaming on/off status.
3.When folded and then expanded on the left side under login status, it disappears directly. However, under non-login status, it folds and expands normally.
https://youtu.be/f_xL_ndWMpk

**Comment by vekvoid** [comment]
Hi, thanks for your feedback.

> 1.It often doesn't trigger; there is a chance it will only appear normally when the cursor is placed above.

This also happens to me, sometimes it doesn't load and I have to reload de page. I will find a better way to load it.
Regarding the cursor thing, never happened to me. I will try to reproduce it using Opera.

> 2.Channel status doesn't update regularly, including changes in the number of viewers and the streaming on/off status.

This is a missing feature. I will try to implement it this weekend.

> 3.When folded and then expanded on the left side under login status, it disappears directly. However, under non-login status, it folds and expands normally.
https://youtu.be/f_xL_ndWMpk

I thought no one would use this alongside a twitch account. I will fix it as soon as I can.

**Comment by vekvoid** [comment]
I fixed `1` can you test it? If doesn't work let me know here #5. I also implemented `2` but I have to improve it (#8).

I will check `3` next week.

**Comment by topfishowo** [comment]
> I fixed `1` can you test it? If doesn't work let me know here #5. I also implemented `2` but I have to improve it (#8).
> 
> I will check `3` next week.

Can't add pinned streamer.
![image](https://github.com/vekvoid/UserScripts/assets/78526289/756874af-807a-48af-96cb-47c062fda2b0)

**Comment by vekvoid** [comment]
> Can't add pinned streamer.

Fixed in `v1.1.1`.

**Comment by vekvoid** [comment]
All issues fixed in `v1.2.0`. Thank you for your feedback!

**Comment by topfishowo** [comment]
It seems that the scheduled status update feature is not functioning.
