### ISSUE TITLE
[Twitch Pinned Streamers] Update streamer info regularly

### ISSUE THREAD

**Issue by vekvoid** [vekvoid/UserScripts#6]
> 2.Channel status doesn't update regularly, including changes in the number of viewers and the streaming on/off status.

Fetch streamer viewers, online status and category every 5 minutes.
Also only fetch if the tab is visible to prevent unnecessary background requests.

Related #4

**Comment by topfishowo** [comment]
It seems that the scheduled status update feature is not functioning.
