### ISSUE TITLE
[Twitch Pinned Streamers] Disappears on hiding sidebar while logged in

### ISSUE THREAD

**Issue by vekvoid** [vekvoid/UserScripts#7]
> 3.When folded and then expanded on the left side under login status, it disappears directly. However, under non-login status, it folds and expands normally.
https://youtu.be/f_xL_ndWMpk

When hiding the sidebar while logged in with a Twitch account, the whole "Pinned Streamers" section disappears and doesn't show again when the sidebar is expanded again.

Related #4

**Comment by topfishowo** [comment]
The position shifts when logged in, and it may also need to be corrected accordingly.
![image](https://github.com/vekvoid/UserScripts/assets/78526289/c771e13e-e1cd-43d7-80eb-d0316abd0f45)

**Comment by vekvoid** [comment]
Fixed in `v1.2.0`. Don't hesitate to reopen the issue if you find any error.
